version: '3.8'

networks:
  testnet:
    driver: bridge

services: 
  node1:
    container_name: node1
    build:
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      - BINDADDR=0.0.0.0
      - PORT=7480
      - RAFTPORT=8000
      - MLPORT=7946
    ports:
      - "7480:7480"
      - "7946:7946"
      - "8000:8000"
    networks:
      - testnet