version: '3.8'

networks:
  testnet:
    driver: bridge

services: 
  node1:
    container_name: node1
    build:
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      - PORT=7480
      - RAFTPORT=8000
      - MLPORT=7946
      - KEY=""
      - CERT=""
      - SERVERID=1
      - PLUGINDIR=/usr/local/lib/memstore
      - INMEMORY=-inMemory
    ports:
      - "7480:7480"
      - "7946:7946"
      - "8000:8000"
    networks:
      - testnet

  node2:
    container_name: node2
    build:
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      - PORT=7480
      - RAFTPORT=8000
      - MLPORT=7946
      - KEY=""
      - CERT=""
      - SERVERID=2
      - JOINADDR=node1:7946
      - PLUGINDIR=/usr/local/lib/memstore
    ports:
      - "7481:7480"
      - "7947:7946"
      - "8001:8000"
    networks:
      - testnet

  node3:
    container_name: node3
    build:
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      - PORT=7480
      - RAFTPORT=8000
      - MLPORT=7946
      - KEY=""
      - CERT=""
      - SERVERID=3
      - JOINADDR=node1:7946
      - PLUGINDIR=/usr/local/lib/memstore
    ports:
      - "7482:7480"
      - "7948:7946"
      - "8002:8000"
    networks:
      - testnet

  node4:
    container_name: node4
    build:
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      - PORT=7480
      - RAFTPORT=8000
      - MLPORT=7946
      - KEY=""
      - CERT=""
      - SERVERID=4
      - JOINADDR=node1:7946
      - PLUGINDIR=/usr/local/lib/memstore
    ports:
      - "7483:7480"
      - "7949:7946"
      - "8003:8000"
    networks:
      - testnet

  node5:
    container_name: node5
    build:
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      - PORT=7480
      - RAFTPORT=8000
      - MLPORT=7946
      - KEY=""
      - CERT=""
      - SERVERID=5
      - JOINADDR=node1:7946
      - PLUGINDIR=/usr/local/lib/memstore
    ports:
      - "7484:7480"
      - "7950:7946"
      - "8004:8000"
    networks:
      - testnet