# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

permissions: write-all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.4'

    - name: Build
      run: go build -v ./cmd/main.go

    - name: Test
      run: go test -coverprofile=coverage.out -v ./...

    - name: Test for Data Race
      run: go test ./... --race

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        directory: ./coverage
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: EchoVault/EchoVault

    - name: Go report card
      uses: creekorful/goreportcard-action@v1.0

